# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "PietSmiet FanClub"
copyright: "&copy; 2015-2016 - PietSmiet FanClub Deutschland e.V."
baseurl: "/"
url: "https://www.pietsmiet.club"

# Build settings
markdown: kramdown
include: ['_pages']
exclude: ['Dockerfile', 'default.conf']
